language: java
sudo: required

# We need Docker.
services:
  - docker

# We need a recent version of Docker.
# At the time this file was created, Travis CI still uses Docker 1.8
# while we need at least Docker 1.9 (and --build-arg parameters).
before_install:  
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

# Skip the default Maven command launched by Travis.
# By default, it is "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install: true

# One build for the agent, one for the DM.
env:
  - pckg=dm
  - pckg=agent

# Run the scripts against the latest version version.
script:
  - cd meta-scripts && ./build.sh "${pckg}" && ./verify.sh "${pckg}"
